project:
  name: quickstart-evidian-safekit
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  quickstart-evidian-safekit-mirror-Linux:
    parameters:
      AvailabilityZones: $[alfred_getaz_3]
      KeyPairName: $[taskcat_getkeypair]
      CAservPwd: $[taskcat_genpass_8A]
      OSType: Linux
      RemoteAccessCIDR: 0.0.0.0/0
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-evidian-safekit/
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/safekit-mirror.template.yaml
  quickstart-evidian-safekit-mirror-Winmdows:
    parameters:
      AvailabilityZones: $[alfred_getaz_2]
      KeyPairName: $[taskcat_getkeypair]
      CAservPwd: $[taskcat_genpass_8A]
      OSType: Windows
      RemoteAccessCIDR: 0.0.0.0/0
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-evidian-safekit/
    regions:
    - us-east-2
    s3_bucket: ''
    template: templates/safekit-mirror.template.yaml
  quickstart-evidian-safekit-farm-Linux:
    parameters:
      AvailabilityZones: $[alfred_getaz_3]
      KeyPairName: $[taskcat_getkeypair]
      CAservPwd: $[taskcat_genpass_8A]
      OSType: Linux
      RemoteAccessCIDR: 0.0.0.0/0
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-evidian-safekit/
    regions:
    - us-west-2
    s3_bucket: ''
    template: templates/safekit-farm.template.yaml
  quickstart-evidian-safekit-farm-Winmdows:
    parameters:
      AvailabilityZones: $[alfred_getaz_2]
      KeyPairName: $[taskcat_getkeypair]
      CAservPwd: $[taskcat_genpass_8A]
      OSType: Windows
      RemoteAccessCIDR: 0.0.0.0/0
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-evidian-safekit/
    regions:
    - us-west-1
    s3_bucket: ''
    template: templates/safekit-farm.template.yaml