AWSTemplateFormatVersion: '2010-09-09'
Description: SafeKit Linux EC2 instance subtemplate (qs-1qtdda1ae)
Parameters:
  AvailabilityZone:
    Description: Choose an Availability Zone
    Type: AWS::EC2::AvailabilityZone::Name
  PublicSubnet:
    Description: ID of the Public Subnet
    Type: String
  PrivateAddr:
    Description: Instance Private Address
    Type: String
  EIPAllocationId:
    Description: AllocationId of the EIP to associate with this Instance
    Type: String
  SecurityGroup:
    Description: ID of the Security Group
    Type: AWS::EC2::SecurityGroup::Id
  InstanceType:
    Default: t2.micro
    Type: String
  InstanceNum:
    Type: String
  InstanceName:
    Type: String
  StackInstanceProfile:
    Type: String
  StackInstanceRole:
    Type: String
  KeyPairName:
    Description: Public/private key pairs allow you to securely connect to your EC2
      instance after it launches.
    Type: AWS::EC2::KeyPair::KeyName
  CAservPwd:
    Type: String
  ClusterFile:
    Type: String
    Default: ''
  ConfigScript:
    Type: String
    Default: "#!/bin/bash\n"
  ConsoleAddrList:
    Type: String
    Default: ''
  CommandAddrList:
    Type: String
    Default: ''
  IpNamesList:
    Type: String
    Default: ''
  SafekitModuleURL:
    Default: none
    Type: String
  SafekitModuleName:
    Default: none
    Type: String
  Userconfig:
    Default: none
    Type: String
  CertificateCN:
    Default: "SafeKit"
    Type: String
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription:
      Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description:
      S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
      Default: 'us-east-1'
      Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
      Type: String
  QSS3KeyPrefix:
      AllowedPattern: '^[0-9a-zA-Z-/]*$'
      ConstraintDescription:
        Quick Start key prefix can include numbers, lowercase letters,
        uppercase letters, hyphens (-), and forward slash (/).
      Default: quickstart-atos-evidian-safekit/
      Description:
        S3 key prefix for the Quick Start assets. Quick Start key prefix
        can include numbers, lowercase letters, uppercase letters, hyphens (-), and
        forward slash (/).
      Type: String
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  FirstInstance: !Equals
    - !Ref 'InstanceNum'
    - '1'
Mappings:
  AWSAMIRegionMap:
    AMI:
      AMZNLINUX2: amzn2-ami-hvm-2.0.20210126.0-x86_64-gp2
    eu-north-1:
      AMZNLINUX2: ami-0eb6f319b31f7092d
    ap-south-1:
      AMZNLINUX2: ami-08e0ca9924195beba
    eu-west-3:
      AMZNLINUX2: ami-0ea4a063871686f37
    eu-west-2:
      AMZNLINUX2: ami-098828924dc89ea4a
    eu-west-1:
      AMZNLINUX2: ami-0fc970315c2d38f01
    ap-northeast-2:
      AMZNLINUX2: ami-09282971cf2faa4c9
    ap-northeast-1:
      AMZNLINUX2: ami-0992fc94ca0f1415a
    sa-east-1:
      AMZNLINUX2: ami-089aac6323aa08aee
    ca-central-1:
      AMZNLINUX2: ami-075cfad2d9805c5f2
    ap-southeast-1:
      AMZNLINUX2: ami-0e2e44c03b85f58b3
    ap-southeast-2:
      AMZNLINUX2: ami-04f77aa5970939148
    eu-central-1:
      AMZNLINUX2: ami-0a6dc7529cd559185
    us-east-1:
      AMZNLINUX2: ami-047a51fa27710816e
    us-east-2:
      AMZNLINUX2: ami-01aab85a5e4a5a0fe
    us-west-1:
      AMZNLINUX2: ami-005c06c6de69aee84
    us-west-2:
      AMZNLINUX2: ami-0e999cbd62129e3b1
Resources:
  SafeKitServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref 'AvailabilityZone'
      Tags:
        - Key: Name
          Value: !Ref 'InstanceName'
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - AMZNLINUX2
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref 'KeyPairName'
      IamInstanceProfile: !Ref 'StackInstanceProfile'
      NetworkInterfaces:
        - DeviceIndex: '0'
          SubnetId: !Ref 'PublicSubnet'
          PrivateIpAddress: !Ref 'PrivateAddr'
          GroupSet:
            - !Ref 'SecurityGroup'
      UserData: !Base64
        Fn::Join:
          - ''
          - - "#!/bin/bash -ex\n"
            - "yum install -y aws-cfn-bootstrap\n"
            - "wget --no-verbose --retry-connrefused  --random-wait -O /tmp/safekit.bin "
            - "https://support.evidian.com/solutions/downloads/safekit/cloud/platforms/linux/current_versions/safekit_cloud.bin\n"
            - "cd /tmp\n"
            - "chmod +x safekit.bin\n"
            - "./safekit.bin\n"
            - "yum localinstall -y safekit_x86_64_*.rpm\n"
            - !Sub '/opt/aws/bin/cfn-init -v --stack "${AWS::StackName}" --resource SafeKitServer --configsets '
            - !If [FirstInstance, InstallModule, InstallBase]
            - !Sub ' --region ${AWS::Region}'
            - "\n"
              # Signal the status from cfn-init
            - '/opt/aws/bin/cfn-signal -e $? '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource SafeKitServer'
            - '         --region '
            - !Ref 'AWS::Region'
            - |+
            - "\n"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT60M
    Metadata:
      AWS::CloudFormation::Authentication:
        S3AccessCreds:
          type: S3
          roleName: !Ref 'StackInstanceRole'
          buckets: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      AWS::CloudFormation::Init:
        configSets:
          InstallBase:
            - SafeKitInstall
            - PostConfig
          InstallModule:
            - SafeKitInstall
            - MasterConfig
            - ModuleConfig
            - PostConfig
        SafeKitInstall:
          commands:
            caservstart:
              cwd: /opt/safekit/web/bin
              command: !Sub './startcaserv ${CAservPwd}'
        MasterConfig:
          files:
            /tmp/userconfig.xml: 
              source:
                !Sub
                  - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}scripts/${Userconfig}'
                  - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
                    S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
              authentication: S3AccessCreds
            /var/safekit/cluster/cluster.xml:
              content: !Ref 'ClusterFile'
              mode: '000664'
              owner: safekit
              group: safekit
            /opt/safekit/web/conf/ipnames.json:
              content: !Ref 'IpNamesList'
              mode: '000444'
              owner: safekit
              group: safekit
            /opt/safekit/web/conf/ipv6.json:
              content: "[\nnull\n]"
              mode: '000444'
              owner: safekit
              group: safekit
            /opt/safekit/web/conf/ipv4.json:
              content: !Ref 'ConsoleAddrList'
              mode: '000444'
              owner: safekit
              group: safekit
            /opt/safekit/web/conf/cmdaddr.json:
              content: !Ref 'CommandAddrList'
              mode: '000444'
              owner: safekit
              group: safekit
            /opt/safekit/web/bin/uploadcerts:
              content: !Join
                - "\n"
                - - "#!/bin/bash -ev"
                  - cd /opt/safekit/web/bin
                  - export LD_LIBRARY_PATH=/opt/safekit/private/bin
                  - !Sub './initssl sca "/CN=${CertificateCN}"'
                  - !Sub 'userpwd=CA_admin:${CAservPwd}'
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F action=swhttps
                    https://localhost:9001/caserv
                  - for targetip in `cat /opt/safekit/web/conf/cmdaddr.json | awk
                    '/".*",/{ print substr($1,2,length($1)-3);}'`; do
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F file=@/opt/safekit/web/conf/cacert.crt
                    -F action=import -F target=T_CA -F add=yes https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F file=@/opt/safekit/web/conf/cacert.crt
                    -F action=import -F target=T_CCA -F add=yes https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F file=@/opt/safekit/web/conf/server.crt
                    -F action=import -F target=T_SC -F add=yes https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F file=@/opt/safekit/web/conf/server.key
                    -F action=import -F target=T_SK -F add=yes https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F file=@/opt/safekit/web/conf/admin.crt
                    -F action=import -F target=T_CC -F add=yes https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F file=@/opt/safekit/web/conf/admin.key
                    -F action=import -F target=T_CK -F add=yes https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F file=@/opt/safekit/web/conf/proxy.crtkey
                    -F action=import -F target=T_PCCK -F add=yes https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F file=@/opt/safekit/web/conf/sslclient.crl
                    -F action=import -F target=T_CRL -F add=yes https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F action=swhttps
                    https://$targetip:9001/caserv
                  - /opt/safekit/private/bin/curl.exe -k -u $userpwd -X POST -F action=shutdown
                    https://$targetip:9001/caserv
                  - done
              mode: '000774'
              owner: safekit
              group: safekit
          commands:
            1-uploadcerts:
              command: /opt/safekit/web/bin/uploadcerts
            2-clusterconf:
              command: /opt/safekit/safekit cluster config
            3-clusterdeploy:
              command: /opt/safekit/safekit -H "*" -G
        ModuleConfig:
          commands:
            1-moduledoanload:
              command: !Sub '/opt/safekit/safekit -r curl.exe --insecure --output
                /var/safekit/tmp/module.safe "${SafekitModuleURL}"'
            2-moduleinstall:
              command: !Sub '/opt/safekit/safekit module install -m ${SafekitModuleName}
                /var/safekit/tmp/module.safe'
            3-modulecleaninstall:
              command: rm -f /var/safekit/tmp/module.safe
        PostConfig:
          files:
            /var/safekit/tmp/safeconfig.sh:
              content: !Ref 'ConfigScript'
              mode: '000554'
              owner: safekit
              group: safekit
          commands:
            1-postconfig:
              command: /var/safekit/tmp/safeconfig.sh
  EIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref 'SafeKitServer'
      AllocationId: !Ref 'EIPAllocationId'
Outputs:
  InstanceId:
    Description: Id of instance
    Value: !Ref 'SafeKitServer'
